# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('i2c', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pir_enabled', models.BooleanField(default=False)),
                ('test_active', models.BooleanField(default=False)),
                ('on_delay', models.IntegerField(default=10)),
                ('slug', models.SlugField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2c.Device')),
            ],
        ),
    ]
