# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-28 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zone',
            old_name='zone',
            new_name='name',
        ),
    ]
