# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('status', models.IntegerField()),
                ('config', models.IntegerField()),
            ],
        ),
    ]
