# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0002_lighthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighthistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
