# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('i2c', '0001_initial'),
        ('lighting', '0004_auto_20170523_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightingState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('config', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='i2c.Device')),
            ],
            options={
                'verbose_name_plural': 'LightingState',
            },
        ),
        migrations.DeleteModel(
            name='LightHistory',
        ),
    ]
