# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighting', '0005_auto_20170530_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightingstate',
            name='config',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lightingstate',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
