# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
