# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateField()),
                ('value_open', models.DecimalField(decimal_places=4, max_digits=9)),
                ('value_close', models.DecimalField(decimal_places=4, max_digits=9)),
                ('value_adjust', models.DecimalField(decimal_places=4, max_digits=9)),
                ('value_usage', models.DecimalField(decimal_places=4, max_digits=9)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Resource')),
            ],
            options={
                'verbose_name_plural': 'ResourceEntries',
            },
        ),
        migrations.CreateModel(
            name='ResourceValueFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.IntegerField(blank=True, null=True)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('billing_factor', models.DecimalField(decimal_places=4, max_digits=9)),
                ('status_value', models.DecimalField(decimal_places=4, max_digits=9)),
                ('factor', models.DecimalField(decimal_places=4, max_digits=9)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy.Resource')),
            ],
        ),
    ]
